### PR TITLE
Update jquery-ui dependency

### PR DESCRIPTION
**Pull request by jbcden**

### CODE REVIEW

**Comment by bsiegel** [comment]
You'll want to use SourceTree or similar to stage only the jquery-ui related changes. Some unrelated changes snuck into this PR.

**Comment by jbcden** [comment]
@bsiegel I just wanted to get rid of the debugger gem. would you prefer a separate PR or just a separate commit?

**Comment by bsiegel** [comment]
I'd prefer not to commit that change, trying to keep this fork as close to upstream as possible.

**Comment by jbcden** [comment]
will do

**Comment by jbcden** [comment]
@bsiegel addressed in ffdc7334cc7dbf5ddd2ee30f847ed110ea5ecb28

**Comment by bsiegel** [comment]
Still need to include the parts of the Gemfile.lock that have changed, that are related to adding jquery-ui-rails.

**Comment by jbcden** [comment]
Addressed in da5515b

**Comment by bsiegel** [comment]
:+1: squash those commits and mege

**Pull request merged**
